# Site settings
title: Projet CAMLEoN
name: Projet CAMLEoN
description:
  Citizens and Academics using Machine Learning for Ecology and eNergy - CAMLEoN
baseurl: "/" # the subpath of your site, e.g. /blog

twitter_username:
github_username:  camleon
email:

# Build settings
markdown: kramdown
